### ISSUE TITLE
Roadmap to 4.0.0

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/generator-brei-gulp#1]
We need to document what features we need from the current generator in the gulp generator, and what new features we want.

For example, we'll want to switch to a postcss approach for autoprefixing and maybe cssnano for minification, instead of just migrating over autoprefixer and cssmin.

## Prerequisites before development
- [ ] Release version 3.2.0 of Grunt generator to fix all current issues and critical feature requests.
- [ ] Update documentation on Grunt generator and related repos.

## Feature List
- [ ] Modernizr 3.x Custom Build
- [ ] GUI Menu to select sub-generator task
- [ ] Handlebars/Templating Language build into static pages
- [ ] Minify JS
- [ ] Babel/ES6 translation
- [ ] Minify CSS
- [ ] Autoprefix CSS

cc: @Sean-BREI

**Comment by nessthehero** [comment]
I'm going to update my top comment with any tasks we need to accomplish before we can kick off this generator, and I also want to document the full feature list of the generator so that we capture everything. Every little thing the generator does, I want to document. E.g. "Builds handlebar files into static pages", "Shows helpful menu on initialization", etc.

**Comment by nessthehero** [comment]
We might consider something other than Assemble for the templates.

I would highly prefer something that already uses handlebars so that we can migrate existing templates, but I am open to using something like Jade.

**Comment by nessthehero** [comment]
This issue was moved to BarkleyREI/generator-brei-app#211
